### ISSUE TITLE
authtoken Jupyter

### ISSUE THREAD

**Issue by ghost** [splunk/splunk-mltk-container-docker#1]
Hello @pdrieger ,

  How do I retrieve the pre-defined authToken for the Jupyter notebook?

Currently starting the GPU container:latest and can not login to Jupyter as it asks for a login pass.

Thank you!

**Comment by pdrieger** [comment]
Hi RANGERBEE, the default PW for Jupyter is Splunk4DeepLearning, documented in the Splunk Deep Learning Toolkit app itself. You can change it from the [config file](https://github.com/splunk/splunk-mltk-container-docker/blob/master/config/jupyter_notebook_config.py) in this repo to set your own password. Hope this is helpful.
