### ISSUE TITLE
 Error in 'fit' command: Error while initializing algorithm "MLTKContainer": Failed to load algorithm "mltkc.MLTKContainer".

### ISSUE THREAD

**Issue by williake** [splunk/splunk-mltk-container-docker#18]
I am trying to set up Deep Learning toolkit on Splunk Cloud using Azure Kubernetes Service. I am able to connect to the containers and launch jupyter notebook, however when I try to execute an example model, the following error message is recieved,

Error in 'fit' command: Error while initializing algorithm "MLTKContainer": Failed to load algorithm "mltkc.MLTKContainer".

The algorithm that is used in the example is present in the app/models folder in the Jupyter notebook.

Any thoughts on what might be wrong here?
Any help is much appreciated.

**Comment by williake** [comment]
We found out that the error was caused by incompability in version 3.6.0 of Deep learning toolkit ,Splunk Machine Learning Toolkit 5.3.0, and Python for Scientific Computing 3.0.1.

This can be fixed in Splunk Enterprise by upgrading to 3.7.0 of  Deep learning toolkit
Alternatively Splunk Machine Learning Toolkit can be downgraded to 5.2.2 and Python for Scientific Computing can be downgraded to 2.0.2.

This is however still a problem in Splunk Cloud since it's not possible to manually choose which version to install

**Comment by pdrieger** [comment]
Thanks for flagging and documenting this. Noting it for next releases and future cloud vetting of DLTK.
