### ISSUE TITLE
Conflict among packages while building the image 3.9 (CPU)

### ISSUE THREAD

**Issue by alexllobet** [splunk/splunk-mltk-container-docker#25]
Greetings,

I have cloned the repository and used the following command to build the image **3.9 with CPU**:
`./build.sh golden-image-cpu {mylocalrepo/} {version}` 
With and without sudo.

However, it seems to be a problem with the version of some of the packages, yielding to conflicts among them. The tail of the output is as follows:

>`Package scikit-image conflicts for:
>shap -> scikit-image
anaconda==2020.11 -> scikit-image==0.17.2[build='py37hdf5156a_0|py38hdf5156a_0']
lime -> scikit-image[version='>=0.12']
datashader -> scikit-image

>Package google-auth-oauthlib conflicts for:
tensorflow -> tensorboard=2.9 -> google-auth-oauthlib[version='0.4.1|>=0.4.1,<0.5|>=0.4.1']
tensorboard -> google-auth-oauthlib[version='0.4.1|>=0.4.1,<0.5|>=0.4.1']
tensorflow-base -> tensorboard=2.9 -> google-auth-oauthlib[version='0.4.1|>=0.4.1,<0.5']

>Package cymem conflicts for:
spacy==2.3.2 -> cymem[version='>=2.0.2,<2.1.0']
thinc -> cymem[version='>=1.30,<1.32|>=2.0.2,<2.1.0|>=2.0.2,<3.0.0']
preshed -> cymem[version='>=1.30,<1.32|>=2.0.2,<2.1.0']

>Package appdirs conflicts for:
prometheus_client -> twisted -> appdirs[version='>=1.4.0']
mlflow -> docker-py[version='>=4.0.0'] -> appdirs[version='>=1.4.3']
docker-py -> appdirs[version='>=1.4.3']

>Package convertdate conflicts for:
holidays -> convertdate[version='>=2.3.0']
fbprophet -> convertdate[version='>=2.1.2']
fbprophet -> holidays[version='>=0.10.2'] -> convertdate[version='>=2.3.0']

>Package wasabi conflicts for:
spacy==2.3.2 -> wasabi[version='>=0.4.0,<1.1.0']
thinc -> wasabi[version='>=0.0.9,<1.1.0|>=0.4.0,<1.1.0|>=0.8.1,<1.1.0']
spacy==2.3.2 -> thinc==7.4.1 -> wasabi[version='>=0.0.9,<1.1.0']

>Package ephem conflicts for:
lunarcalendar -> ephem[version='>=3.7.5.3']
fbprophet -> lunarcalendar[version='>=0.0.9'] -> ephem[version='>=3.7.5.3']

>Package hijri-converter conflicts for:
holidays -> hijri-converter
fbprophet -> holidays[version='>=0.10.2'] -> hijri-converter

>Package immutables conflicts for:
distributed -> contextvars -> immutables[version='>=0.9']
thinc -> contextvars[version='>=2.4,<3'] -> immutables[version='>=0.9']

>Package smart_open conflicts for:
nltk -> gensim -> smart_open[version='>=1.2.1|>=1.8.1']
node2vec -> gensim -> smart_open[version='>=1.2.1|>=1.8.1']
gensim -> smart_open[version='>=1.2.1|>=1.8.1']The following specifications were found to be incompatible with your system:

 > feature:/linux-64::__glibc==2.31=0
 > feature:|@/linux-64::__glibc==2.31=0
 > aiohttp -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > argon2-cffi -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > astropy -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > binutils_impl_linux-64 -> libstdcxx-ng[version='>=4.9'] -> __glibc[version='>=2.17']
 > bitarray -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > blosc -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > bottleneck -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > brotlipy -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > bzip2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > c-ares -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > cairo -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > cffi -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > cftime -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > conda-package-handling -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > cryptography -> libgcc-ng -> __glibc[version='>=2.17']
 > curl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > cxx-compiler -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > cymem -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > cython -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > cython-blis -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > cytoolz -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > dask-ml -> libgcc-ng[version='>=7.2.0'] -> __glibc[version='>=2.17']
 > dbus -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > ephem -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > expat -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > fastcache -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > fbprophet -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > fontconfig -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > freetype -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > fribidi -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > frozenlist -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > gcc_impl_linux-64 -> libgcc-devel_linux-64==11.2.0=h1234567_1 -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
 > gensim -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > gevent -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > glib -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > gmp -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > gmpy2 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > graphite2 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > greenlet -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > grpcio -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > gst-plugins-base -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > gstreamer -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > h5py -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > harfbuzz -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > hdf4 -> libgcc-ng[version='>=7.2.0'] -> __glibc[version='>=2.17']
 > hdf5 -> libgfortran-ng -> __glibc[version='>=2.17']
 > icu -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > jbig -> libgcc-ng[version='>=7.2.0'] -> __glibc[version='>=2.17']
 > jpeg -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > kiwisolver -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > krb5 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > lazy-object-proxy -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > lcms2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > libarchive -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libcurl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libedit -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libffi -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libgcc-ng -> __glibc[version='>=2.17']
 > libgfortran-ng -> __glibc[version='>=2.17']
 > liblief -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libllvm10 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > libnetcdf -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libpng -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > libprotobuf -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libsodium -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > libspatialindex -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > libssh2 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libstdcxx-ng -> __glibc[version='>=2.17']
 > libtiff -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libtool -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libuuid -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libxcb -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libxgboost -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libxml2 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > libxslt -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > llvmlite -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > lxml -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > lz4-c -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > lzo -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > markupsafe -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > matplotlib -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > matplotlib-base -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > mistune -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > mkl-service -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > mkl_fft -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > mkl_random -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > mpc -> libgcc-ng[version='>=7.2.0'] -> __glibc[version='>=2.17']
 > mpfr -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > msgpack-python -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > multidict -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > murmurhash -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > ncurses -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > netcdf4 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > nodejs[version='>=10.0.0'] -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > numba -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > numexpr -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > numpy -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > numpy-base -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > openssl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pandas -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pango -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > patchelf -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pcre -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pillow -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pixman -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pomegranate -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > preshed -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > protobuf -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > psutil -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > py-lief -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > py-xgboost -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pycosat -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > pycurl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pyodbc -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pyqt -> qt-main=5.15 -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
 > pyrsistent -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pystan -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pytables -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > python=3.8 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pytorch -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
 > pywavelets -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pyyaml -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > pyzmq -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > qt -> qt-main[version='>=5.15,<6'] -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
 > readline -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > regex -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > ruamel_yaml -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > scikit-image -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > scikit-learn -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > scipy -> libgfortran-ng -> __glibc[version='>=2.17']
 > shap -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > sip -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > spacy==2.3.2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > sqlalchemy -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > sqlite -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > srsly -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > statsmodels -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > tbb -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > tensorboard -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > tensorflow-base -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > theano-pymc -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > thinc -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > tifffile -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > tk -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > tornado -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > tslearn -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > ujson -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > unixodbc -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > wrapt -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > xgboost -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > xz -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > yaml -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > yarl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > zeromq -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
 > zlib -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > zope.interface -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
 > zstd -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

>Your installed version is: 2.31

>The command '/bin/sh -c conda install pyg -c pyg' returned a non-zero code: 1`

Actions taken so far:
- Remove all the images created in Docker and rebuild.
- Clone again the repository
- Include an update pip and conda command at the beginning of the Dockerfile
- Try on different computers and O.S (Ubuntu 20.04 and Debian)
- Force Docker to not use cache

Please, find attached a screenshot of the problem.

<img width="806" alt="problem_dltk" src="https://user-images.githubusercontent.com/26059063/193252797-285e6c99-d6ff-4b71-9511-ed0d9541a516.PNG">

Thank you very much in advanced.

**Comment by pdrieger** [comment]
Hi @alexllobet, the conda install pyg is causing the conflict. Have you tried building without pyg? Please watch out for updates in the next week when new version goes live including updates on the Dockerfiles.

**Comment by alexllobet** [comment]
Good morning @pdrieger, thanks for your answer. Unfortunately, the build also failed without the pyg package. Nevertheless, I finally managed to build the image with some changes in the Dockerfile. One of the main conflicts was with tensorboard. 
I will create a PR, just in case you want to try it.
Thank you very much.
