### ISSUE TITLE
Migrate framework from PIP to Conda

### ISSUE THREAD

**Issue by anthonygtellez** [splunk/splunk-mltk-container-docker#3]
There's a 8x performance boost by switching from PIP libraries to Conda libraries. 

https://towardsdatascience.com/stop-installing-tensorflow-using-pip-for-performance-sake-5854f9d9eb0c

We should stop installing libs via PIP and ensure we are installing Tensorflow + dependencies in the dockerfile using conda.

**Comment by pdrieger** [comment]
Most of recent DLTK images rely on conda wherever possible. TF and PyTorch is installed via conda in the golden image.
