### ISSUE TITLE
DSDL - Kmeans yields different results for fit and apply commands

### ISSUE THREAD

**Issue by Schiggy-3000** [splunk/splunk-mltk-container-docker#30]
My goal is to cluster a dataset with kmeans and then assign new observations to center points form my kmeans model.

I built the model in Jupyter Notebooks and everything compiled just fine. I then wanted to check my model for possible logical errors. To this end, I use the same dataset in the | fit and | apply command. See pictures down below.

To my understanding, this should yield the exact same results. However, it does not. | fit creates 5 clusters and assigns observations to each cluster. | apply on the other hand only assigns observations to 3 out of the 5 clusters.  I already checked the documentation that outlines what they both do:

https://docs.splunk.com/Documentation/MLApp/5.3.3/User/Understandfitandapply

I thoroughly checked whether I have null values, non-numeric fields that might get converted, etc. but I could not figure out why fit & apply wouldn't yield the same result.

Following the code, dataset and SPLs I used (the _AAA_Pipeline_V3.py_ file in _srv/app/model_ is also generated properly).

- Jupyter notebook code: [AAA_Pipeline_V3.zip](https://github.com/splunk/splunk-mltk-container-docker/files/10141118/AAA_Pipeline_V3.zip)
- Used dataset: [wineventlog_for_issue.csv](https://github.com/splunk/splunk-mltk-container-docker/files/10141070/wineventlog_for_issue.csv)
- SPL results:
![fit_model](https://user-images.githubusercontent.com/93184896/205294901-d8ca71e8-02f6-4f72-80c5-0744dd5f17b0.PNG)
![apply_model](https://user-images.githubusercontent.com/93184896/205294933-2ac0e252-989a-4394-bbcc-f88cbbb75cd1.PNG)

**Comment by Schiggy-3000** [comment]
Update:

The first test I did was to check where the issue might stem from: Inside Splunks SPL or in the Jupyter Notebook. For this, I tested whether Jupyter Notebook provides the same clustering results from the fitted model and the loaded model. Indeed the results are the same in both cases. Hence, I persume somewhere inside the SPL different models are used for **| fit** and **| apply**.

`fit_model = fit(model, df, param)
pred_fit_model = fit_model['kmeans'].predict(df)

apply_model = load('pipeline_v3')
pred_apply_model = apply_model['kmeans'].predict(df)

(pred_fit_model == pred_apply_model).all()`

**Comment by pdrieger** [comment]
Thanks for posting @Schiggy-3000 let me look into that next week!

**Comment by pdrieger** [comment]
Hi @Schiggy-3000 was able to look earlier into it and I was able to replicate your issue and solved it: in your notebook's def apply function you run `predictions = model['kmeans'].predict(df)` and simply take the whole df dataframe object which contains more columns than the actual ones that you defined in your SPL with `fe_*`. If you investigate the `params` object in the notebook you should find the explicit list of `feature_variables` that you actually want your kmeans to apply to. As shown in other examples you can access the feature variables and filter the incoming df. I solved the issue by adding one line before you compute the predictions in your def apply like this:

def apply(model, df, param):
    **X = df[param['feature_variables']]**
    predictions = model['kmeans'].predict(X)


Running the fit and apply with this returns the exact same cluster labels and their count is consistent.

Hope this helps you to resolve the issue. Have a nice weekend :)
