### ISSUE TITLE
App breaks at Splunk Version >= 9.1.0

### ISSUE THREAD

**Issue by mslookup** [splunk/splunk-mltk-container-docker#33]
Seems the app breaks when using a Splunk Version >= 9.1.0.

App is showing some nasty Java Script errors (ref: Screenshot).

To reproduce: 
- Install Splunk >= 9.1.0 (single instance is sufficient)
- Install MLTK, Python app, DSDL app
- Configure DSDL app container environment, Start a container, go back to app start page

![grafik](https://github.com/splunk/splunk-mltk-container-docker/assets/66677275/ac547253-6425-43bc-831b-5f28e4cb28d2)

BR,
mslookup

**Comment by heyitsmikey128** [comment]
They did some Javascript Voodoo without putting anything in the release notes for 9.1.

Go here: <host>/en-US/manager/splunk_monitoring_console/internal_library_settings

Unrestrict the Unsupported Hotlinked Imports and you should be good.

**Comment by pdrieger** [comment]
Hi @mslookup thanks for raising this issue and we got to hear it a few more times recently in combination with Splunk 9.1. We already worked out a fix for this and will include it in the next release of the DSDL app. Meanwhile please check if @heyitsmikey128 solution is workaround - thanks for pointing it out! 👍
