### ISSUE TITLE
Wrong docker hub registry url for transformes-cpu in DSDL 5.1.1

### ISSUE THREAD

**Issue by williake** [splunk/splunk-mltk-container-docker#39]
Hi Philipp!

I get errors when I try to pull the included Transformers CPU (5.1.1) image in Splunk DSDL version 5.1.1

I've noticed that the config for [transformers-cpu] in images.conf has errors in the stanza

[transformers-cpu]
title = Transformers CPU (5.1.1)
image = mltk-container-transformers-cpu:5.1.1
repo = phdrieger/
runtime = none

I think should be changed to

[transformers-cpu]
title = Transformers CPU (5.1.1)
image = mltk-container-golden-cpu-transformers:5.1.1
repo = phdrieger/
runtime = none

for it to correspond correctly with your docker hub registry.

Best regards,
William Ke

**Comment by pdrieger** [comment]
Hi @williake thanks for flagging this, you are absolutely correct, this must have been a left over during some name changes we did in 5.1.1 version. I temporarily fixed it by pushing/mounting the same image on dockerhub also to the phdrieger/mltk-container-transformers-cpu:5.1.1 name. This work around is the fastest way to fix it. We will need to change the name in a future version which takes longer. As reference, please find version tag 5.1.1 here: https://hub.docker.com/repository/docker/phdrieger/mltk-container-transformers-cpu/general - thanks again for raising this!
