### ISSUE TITLE
Jupyterlab permission issue

### ISSUE THREAD

**Issue by ckddyd777** [splunk/splunk-mltk-container-docker#4]
Hi, 

I want to set an environment with splunk and DLTK. But, It doesn't work. (partially)

What I did is as follows : 
 1. Install splunk enterprise
 2. Install docker && run docker (as root)
 3. Install Splunk Machine learnign toolkit and others.
 4. Container Environment Setup (It works.)
 5. Run container
    Container Image : Golden Image GPU (3.2) 
    GPU runtime : nvidia
    Cluster target : docker
    It looks working, but, open JUPYTER LAB, permission error is occured.

Pop up) Permission denied: notebooks/linear_regressor.ipynb 

Any Idea of this issue? I'll waiting for your answer. Thanks.

**Comment by tylerwilliams1010** [comment]
Can you try the following and see if it works?

chmod 777 /var/run/docker.sock

**Comment by pdrieger** [comment]
Hi, if this looks like a file system permission issue then you should check the docker volume and that you're allowed to write to it (which you can also check from within the running container). Hope this helps for troubleshooting?
